# Generated by Django 4.2.4 on 2023-09-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InpuFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibanNumber', models.CharField(max_length=32)),
                ('countryCode', models.CharField(max_length=3)),
            ],
        ),
    ]
