# Generated by Django 4.2.4 on 2023-09-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='InpuFields',
        ),
    ]
